#!/bin/bash

echo "📚 Complete Documentation Overview"
echo "================================="
echo ""
echo "🎯 Database Documentation Structure:"
echo ""
echo "📁 src/database/documentation/"
echo "   └── README.md                 # Database overview & configuration"
echo ""
echo "📁 src/modules/booking/documentation/"
echo "   ├── README.md                 # Booking module index"
echo "   └── booking-api.md            # Complete booking API docs"
echo ""
echo "📁 src/modules/user/documentation/"
echo "   ├── README.md                 # User module index"
echo "   └── user-api.md               # Complete user API docs"
echo ""
echo "📁 src/modules/hotel/documentation/"
echo "   ├── README.md                 # Hotel module index"
echo "   └── hotel-api.md              # Complete hotel API docs"
echo ""
echo "🚀 Available Operations:"
echo ""
echo "📝 Mutations:"
echo "   • createUser - Register new user"
echo "   • createHotel - Register new hotel"
echo "   • createBooking - Create hotel booking"
echo ""
echo "🔍 Queries:"
echo "   • user, users - User operations"
echo "   • hotel, hotels, searchHotels - Hotel operations"
echo "   • booking, bookings, bookingsByUser, bookingsByHotel - Booking operations"
echo ""
echo "📖 Documentation Features:"
echo "   ✅ Complete GraphQL queries with variables"
echo "   ✅ Response examples with real data"
echo "   ✅ Error handling scenarios"
echo "   ✅ Business rules and validation"
echo "   ✅ Relationship documentation"
echo "   ✅ Type definitions and examples"
echo ""
echo "🎮 Interactive Testing:"
echo "   • GraphQL Playground: http://localhost:3000/graphql"
echo "   • Apollo Sandbox: https://studio.apollographql.com/sandbox"
echo ""
echo "📋 Quick Start Commands:"
echo "   npm run start:dev     # Start development server"
echo "   npm run db:migrate    # Run database migrations"
echo "   npm run db:seed       # Seed database with demo data"
echo ""
echo "📄 Main Documentation Files:"
echo "   • GRAPHQL-DOCUMENTATION.md - GraphQL overview guide"
echo "   • Each module has complete API documentation"
echo "   • Database configuration and setup docs"
echo ""
echo "🎯 All documentation includes:"
echo "   • Ready-to-use GraphQL examples"
echo "   • Complete request/response examples"
echo "   • Error handling scenarios"
echo "   • Business rules and constraints"
echo "   • Type safety information"
echo ""
echo "🚀 Your GraphQL API is now fully documented!"
